version: '3.8'
services:

  mongodb:
    image: mongo:7.0.2-jammy
    container_name: mongodb-order-service
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - humf-order-service-network
  
  order-service:
      build: ./
      container_name: order-service
      env_file:
        - .env
      ports:
        - 5000:5000
      depends_on:
        - mongodb
      volumes:
        - ./src:/app/src
      command: npm run start:dev
      networks:
        - humf-order-service-network

networks:
  humf-order-service-network:
    driver: bridge