version: '3.8'
services:
  # order-service:
  #   build: ./
  #   image: order-service
  #   ports:
  #     - 4003:4000
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - .:/src
  #   networks:
  #     - humf-order-service-network

  mongodb:
    image: mongo:7.0.2-jammy
    ports:
      - 27100:27017
    volumes:
      - dbdata:/data/db
    networks:
      - humf-order-service-network

volumes:
  dbdata:

networks:
  humf-order-service-network:
    driver: bridge