version: '3.8'
services:

  mongodb:
    image: mongo:7.0.2-jammy
    container_name: mongodb-order-service
    expose:
      - 27017
    volumes:
      - dbdata:/data/db
    networks:
      - humf-order-service-network
  
  order-service:
      build: ./
      image: order-service:1.0
      container_name: order-service
      env_file:
        - .env
      ports:
        - ${ORDER_SERVICE_PORT}:4000
      depends_on:
        - mongodb
      command: npm run start:dev
      networks:
        - humf-order-service-network

volumes:
  dbdata:

networks:
  humf-order-service-network:
    driver: bridge